### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by ozh** [emilkje/jquery.selectText#1]
Hi

Not sure if you still want to maintain this, but as far as I can tell it doesn't work (anymore?) with latest jQuery. Nothing happens. Demo: http://jsfiddle.net/ozhy/yV8Mk/

Cheers

Ozh

**Comment by emilkje** [comment]
Thank you, though it is still working with other none interactable elements such as span, li, a, div and so on. But I should improve this when I have the time :) thanks again
